[build]
  publish = "out"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/join/:roomId"
  to = "/join/[roomId].html"
  status = 200

[[redirects]]
  from = "/game/:roomId"
  to = "/game/[roomId].html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200